# POST http://localhost:3000/movies.json
# Content-Type: application/json

# {
#   "title": "test from http",
#   "plot": "test from http",
#   "year": "1234",
#   "director": "nobody",
#   "english": "true"
# }

# ### 
# # update
# PATCH http://localhost:3000/movies/6.json
# Content-Type: application/json

# {
#   "plot": "edited"
# }

# ###
# # destroy

# DELETE http://localhost:3000/movies/4.json
# Content-Type: application/json

###

POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "test from http",
  "last_name": "test from http",
  "known_for": "1234",
  "age": "12",
  "gender": "male"

}

### 
# update
PATCH http://localhost:3000/actors/7.json
Content-Type: application/json

{
  "age": "22"
}

# ###
# # destroy

# DELETE http://localhost:3000/actors/6.json
# Content-Type: application/json