# POST http://localhost:3000/movies.json
# Content-Type: application/json

# {
#   "title": "test from http",
#   "plot": "test from http",
#   "year": "1234",
#   "director": "nobody",
#   "english": "true"
# }

# ### 
# # update
# PATCH http://localhost:3000/movies/6.json
# Content-Type: application/json

# {
#   "plot": "edited"
# }

# ###
# # destroy

# DELETE http://localhost:3000/movies/4.json
# Content-Type: application/json

### actors create 

POST http://localhost:3000/actors.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzU0NTgxODV9.qZqneM94qp-Skz9KA3up0h4X3ZzfiUkZnc4dWrLtnRk
Content-Type: application/json

{
  "first_name": "B",
  "last_name": "W",
  "known_for": "RED",
  "age": "6",
  "gender": "male",
  "movie_id": "3"
}

### 
# update
PATCH http://localhost:3000/actors/7.json
Content-Type: application/json

{
  "age": "22"
}

###
# destroy

DELETE http://localhost:3000/actors/7.json
Content-Type: application/json

### Users create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "The big gamer",
  "email": "biggamer@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "biggamer@test.com",
  "password": "password"
}
