# POST http://localhost:3000/movies.json
# Content-Type: application/json

# {
#   "title": "test from http",
#   "plot": "test from http",
#   "year": "1234",
#   "director": "nobody",
#   "english": "true"
# }

# ### 
# # update
# PATCH http://localhost:3000/movies/6.json
# Content-Type: application/json

# {
#   "plot": "edited"
# }

# ###
# # destroy

# DELETE http://localhost:3000/movies/4.json
# Content-Type: application/json

###

POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Bruce",
  "last_name": "Willis",
  "known_for": "RED",
  "age": "66",
  "gender": "male",
  "movie_id": "1"
}

### 
# update
PATCH http://localhost:3000/actors/7.json
Content-Type: application/json

{
  "age": "22"
}

###
# destroy

DELETE http://localhost:3000/actors/7.json
Content-Type: application/json